apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claims.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageclass.name }}
  resources:
    requests:
      storage: 5Gi
#  volumeName: {{ .Values.persistentvolume.name }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-nfs-pvc
spec:
  storageClassName: nfs-external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

