apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-nfs-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: nfs-external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

