apiVersion: v1
kind: Secret
metadata:
  name: zetaris-sa-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceaccount.name }}
type: kubernetes.io/service-account-token