apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solrcontent-pvc
spec:
  storageClassName: nfs-external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solrmetadata-pvc
spec:
  storageClassName: nfs-external
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
