#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt-enterprise
#  namespace: kube-system
#spec:
#  acme:
#    server: https://acme-v02.api.letsencrypt.org/directory
#    email: {{ .Values.email }}
#    privateKeySecretRef:
#      name: letsencrypt-enterprise-key
#    solvers:
#      - http01:
#          ingress:
#            class: nginx
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: ca-issuer
 namespace: zetaris
spec:
 selfSigned: {}

