apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lightning-api-alb
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ .Values.clusterissuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/client-body-buffer-size: 500m
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* /internal {
          deny all;
          return 403;
        }
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "server: hide";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Xss-Protection: 1";
      more_set_headers "referrer-policy: no-referrer";
      more_set_headers "Content-Security-Policy: frame-ancestors 'none'";
      more_set_headers "Request-Id: ''";
spec:
  tls:
    - hosts:
        - api.{{ .Values.deploymentname }}.{{ .Values.dnsdomain }}
      secretName: tls-secret-api
  rules:
    - host: api.{{ .Values.deploymentname }}.{{ .Values.dnsdomain }}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: lightning-api-svc
              port:
                number: 8888

