{{- if eq .Values.clusterissuer "letsencrypt-enterprise" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterissuer }}
  namespace: kube-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-enterprise-key
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end }}
---
{{- if eq .Values.clusterissuer "localca" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: {{ .Values.clusterissuer }}
 namespace: kube-system
spec:
 ca: {
   secretName: {{ .Values.certsecret }}
 }
{{- end }}