{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.customerdatapvc }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageclassname }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
{{- end }}