apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.registrysecret.config }}
kind: Secret
metadata:
  name: {{ .Values.registrysecret.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson