---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount.name }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-role-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceaccount.role }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceaccount.name }}
    namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: zetaris-sa-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceaccount.name }}
type: kubernetes.io/service-account-token