apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-ing
  namespace: {{ .Values.airflownamespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ .Values.clusterissuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "server: hide";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Xss-Protection: 1";
spec:
  tls:
    - hosts:
        - airflow.{{ .Values.deploymentname }}.{{ .Values.dnsdomain }}
      secretName: tls-secret-airflow
  rules:
    - host: airflow.{{ .Values.deploymentname }}.{{ .Values.dnsdomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airflow-webserver
                port:
                  number: 8080
