# Default values for lightning-gui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


name : lightning-api
namespace : zetaris
replicas : 1
deploymentname: zetaris
dnsdomain: tanzu.lab
clusterissuer: local-ca-issuer

api:
  image : zetregistry.azurecr.io/lightning-api:main-2.3.2.0-c663958ab30a4d6a62a3e124312343e3f2d655e7
  lightning_api_deploy_mode: internal

secret:
  acrauth : acrcred

service:
  api : lightning-api-svc

claims:
  data: external-nfs-pvc

volumes:
  customerdata : datafabricguicustdata

db:
  METASTORE_DATABASE_URL: jdbc:postgresql://172.16.49.61:5432/metastore?sslmode=require&user=lightning&password=Zetaris100PGPASS
  AUDIT_LOG_DATABASE_URL: jdbc:postgresql://172.16.49.61:5432/audit_log?sslmode=require&user=lightning&password=Zetaris100PGPASS

server:
  lightning_server_url: jdbc:zetaris:lightning@lightning-server-svc:10000

encryption:
  encryption_local_pk_path: /home/zetaris/lightning/password-security/private_key.der
  encryption_local_pubk_path: /home/zetaris/lightning/password-security/public_key.der
