apiVersion: v1
kind: ConfigMap
metadata:
  name: lightning-server-config
  namespace: {{ .Values.namespace }}
data:
  {{- (.Files.Glob "server/*.properties").AsConfig | nindent 2 }}
  {{- (.Files.Glob "server/*.xml").AsConfig | nindent 2 }}