apiVersion: v1
kind: Service
metadata:
  name: lightning-server-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 10000
      targetPort: 10000
  type: LoadBalancer
  selector:
    app: {{ .Values.server.name }}


