apiVersion: v1
kind: Secret
metadata:
  name: lightning-server-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData: 
  jdbc_url: jdbc:postgresql://{{ .Values.postgres.PostgreSQLHost }}:5432/metastore?sslmode=require
  jdbc_driver_class: {{ .Values.postgres.JDBC_DRIVER_CLASS }}
  username: {{ .Values.postgres.DB_USERNAME }}
  password: {{ .Values.postgres.DB_PASSWORD }}
  hibernate.dialect: {{ .Values.postgres.HIBERNATE_DIALECT }}
  auditLog_jdbc_url: jdbc:postgresql://{{ .Values.postgres.PostgreSQLHost }}:5432/audit_log?sslmode=require
  auditLog_jdbc_driver_class: {{ .Values.postgres.JDBC_DRIVER_CLASS }}
  auditLog_username: {{ .Values.postgres.DB_USERNAME }}
  auditLog_password: {{ .Values.postgres.DB_PASSWORD }}
  auditLog_hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  default_admin_password: {{ .Values.ndppassword }}

---
apiVersion: v1
kind: Secret
metadata:
  name: lightning-password-security-encryption-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  private_key.der: {{ .Values.privatekeyder }}
  public_key.der: {{ .Values.publickeyder }}

