apiVersion: v1
kind: Secret
metadata:
  name: lightning-gui-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  NDP_DRIVER_USERNAME: {{ .Values.ndpusername }}
  NDP_DRIVER_PASSWORD: {{ .Values.ndppassword }}
  JDBC_DRIVER : com.zetaris.lightning.jdbc.LightningDriver
  JDBC_URL : jdbc:zetaris:lightning@lightning-server-svc:10000
  ZFILESYSTEM_STAGING: /home/zetaris/customer-data
  CALENDLY_URL: https://calendly.com/d/x4w-yk4-q8b/zetaris-customer-success-touchpoint
  ENABLE_HUBSPOT_TRACKING: 'true'
---
apiVersion: v1
kind: Secret
metadata:
  name: lightning-gui-sso-env-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SSO_REDIRECT_URL: https://ui.{{ .Values.deploymentname }}.{{ .Values.dnsdomain }}
  SSO_SAML2_KEYSTORE_CERTIFICATE_FILE_PATH: /home/zetaris/lightning-gui/sso/certificate.pem
  SSO_SAML2_KEYSTORE_PRIVATE_KEY_FILE_PATH: /home/zetaris/lightning-gui/sso/pkcs8.key

