# Default values for lightning-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name : lightning-solr
namespace: zetaris

solrimage : zetaris/lightning-solr:8.6.0
solrreplicas : 1
registrysecretname: dockerhubcred
