apiVersion: v1
kind: Secret
metadata:
  name: lightning-gui-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  NDP_DRIVER_USERNAME: admin@default.com
  NDP_DRIVER_PASSWORD: {{ .Values.ndp.password }}
  APP_SECRET_KEY: lightning-server-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: lightning-gui-sso-env-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SSO_REDIRECT_URL: http(s)://<YOUR_DNS>.com
  SSO_SAML2_KEYSTORE_CERTIFICATE_FILE_PATH: /home/zetaris/lightning-gui/sso/certificate.pem
  SSO_SAML2_KEYSTORE_PRIVATE_KEY_FILE_PATH: /home/zetaris/lightning-gui/sso/pkcs8.key


