apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.gui.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: INTERNAL_REST_SERVICE_URL
              value: http://lightning-api-svc:8888
            - name: REST_SERVICE_URL
              value: https://api.{{ .Values.deploymentname }}.{{ .Values.dnsdomain }}
            - name: LIGHTNING_SERVER_URL
              value: jdbc:zetaris:lightning@lightning-server-svc:10000
            - name: ZFILESYSTEM_STAGING
              value: {{ .Values.filesystem_staging }}
            - name: CALENDLY_URL
              value: {{ .Values.calendly_url }}        
            - name: SHOW_BUILD_HASH
              value: {{ .Values.show_build_hash | quote }}
            - name: APACHE_AIRFLOW_URL
              value: https://airflow.{{ .Values.deploymentname }}.{{ .Values.dnsdomain }}
            - name: ENABLE_HUBSPOT_TRACKING
              value: {{ .Values.enable_hubspot_tracking | quote }}
          envFrom:
            - secretRef:
                name: lightning-server-secret
            - secretRef:
                name: lightning-gui-config
            - configMapRef:
                name: lightning-general-config
          ports:
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /home/zetaris/customer-data
              name: lightning-customer-data-volume
            - mountPath: /home/zetaris/lightning-gui/conf
              name: lightning-gui-conf-volume
      imagePullSecrets:
        - name: {{ .Values.secret.acrauth }}
      volumes:
        - name: lightning-gui-conf-volume
          configMap:
            name: lightning-gui-config
        - name: lightning-customer-data-volume
          persistentVolumeClaim:
            claimName: {{ .Values.claims.data }}
