apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.api }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: {{ .Values.name }}
