apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.api.image }}
          imagePullPolicy: Always
          env:
            - name: ALLOWED_ORIGINS
              value: https://ui.{{ .Values.deploymentname }}.{{ .Values.dnsdomain }}
            - name: METASTORE_DATABASE_URL
              value: {{ .Values.db.METASTORE_DATABASE_URL }}
            - name: AUDIT_LOG_DATABASE_URL
              value: {{ .Values.db.AUDIT_LOG_DATABASE_URL }}
            - name: LIGHTNING_SERVER_URL
              value: jdbc:zetaris:lightning@lightning-server-svc:10000
            - name: LIGHTNING_API_DEPLOY_MODE
              value: {{ .Values.api.lightning_api_deploy_mode }}
            - name: ENCRYPTION_LOCAL_PRIVATE_KEY_PATH
              value: {{ .Values.encryption.encryption_local_pk_path }}
            - name: ENCRYPTION_LOCAL_PUBLIC_KEY_PATH
              value: {{ .Values.encryption.encryption_local_pubk_path }}
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: password-security-volume
              mountPath: /home/zetaris/lightning/password-security
              readOnly: true
            - mountPath: /home/zetaris/customer-data
              name: lightning-customer-data-volume
  
      imagePullSecrets:
        - name: {{ .Values.secret.dockerhubcred }}
      volumes:
        - name: password-security-volume
          secret:
            defaultMode: 0606
            secretName: api-password-security-encryption-secret
        - name: lightning-customer-data-volume
          persistentVolumeClaim:
            claimName: {{ .Values.claims.data }}
